### ISSUE TITLE
ArviZ InferenceData transformer

### ISSUE THREAD

**Issue by ahartikainen** [rlouf/mcx#32]
Hi, great package.

I wanted to ask if you would be interested with ArviZ link? We currently have many different libraries that we support with `from_xyz` functions. These functions translate original fit results to ArviZ `InferenceData`, and this enables one to use diagnostics, statistics and plots we provide.

https://github.com/arviz-devs/arviz/tree/master/arviz/data

There is `from_dict` function, which can translate dictionaries to `InferenceData` if one wants to try how our library works (or if they have external sampling results).

There is also third option where ArviZ link is implemented by the target library (e.g. PyMC4 does this) and no `from_xyz` function is needed.

We (ArviZ devs) can work together with creating the functionality, but basically creating similar file as `io_pystan` or `io_numpyro` is needed, which has a class which created `InferenceData` and then external functions which help to parse the fit object.

https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pystan.py
https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_numpyro.py

**Comment by rlouf** [comment]
Hi,

Thanks for your interest! Integration with ArviZ is indeed on the roadmap for the first release. I originally thought about implementing my `Trace` class as a subclass of ArviZ's `InferenceData` to provide transparent integration. I am not far enough in the development to be able to tell whether that would be doable/practical and make sense long term, but that is the current aim. All I can say right now is that there will at least be a `io_mcx.py`.

**Comment by rlouf** [comment]
This has become my priority. You can follow the progress in #35.

**Comment by rlouf** [comment]
Merged on master. Currently supports (warmup) posterior, sample_stats and log_likelihood.
