### ISSUE TITLE
switch `import jax.numpy as np` to `import jax.numpy as jnp`

### ISSUE THREAD

**Issue by jeremiecoullon** [rlouf/mcx#55]
This is to keep aligned with the Jax core and the documentation. From [this issue](https://github.com/google/jax/issues/4643): _there has been a bit of a transition in the usage of JAX-flavored numpy from JAX is a drop-in replacement for numpy to JAX is a tool to use beside numpy_.

**Comment by rlouf** [comment]
I assume you meant `jnp`. That's a good point, and it's better to do it before it becomes too complicated.

**Comment by jeremiecoullon** [comment]
> I assume you meant `jnp`. That's a good point, and it's better to do it before it becomes too complicated.

Yes! Just changed it

**Comment by rlouf** [comment]
Waiting to see if the collaboration with PyMC3 and Numpyro happens before making the changes here.

**Comment by rlouf** [comment]
Samplers are being moved to [blackjax](https://github.com/blackjax-devs/blackjax). We will use `jnp` instead of `np` there. Closing.
