### ISSUE TITLE
python packages missing

### ISSUE THREAD

**Issue by jeremiecoullon** [rlouf/mcx#56]
After cloning the repo, starting a fresh venv, and running `pip install .`, there were still a few packages missing:
• `isort`
• `black`
• `flake8`
• `mypy`

After installing these manually, all the tests passed.

**Comment by rlouf** [comment]
Yes I usually don't ship dev dependencies with the repo, but adding a requirements-dev.txt or something like that would be nice indeed.

**Comment by rlouf** [comment]
I added a `requirements-dev.txt` in the repo that installs everything to run the tests, lint the code and build the docs. The same requirements file is now used in the CI so it is run in the same environment as the devs.

cf commit 5e9fc32923e985d03ba15e8f4a6772c9e7cc6408
