### ISSUE TITLE
Replace `jax.numpy` abbreviation from `np` to `jnp` 

### ISSUE THREAD

**Issue by sidravi1** [rlouf/mcx#72]
`jax` and `numpyro` both use `jnp` for `jax.numpy` and `np` for `numpy`. To avoid confusion, we should switch to their convention:

Need to go through the entire codebase, change these lines:

`import jax.numpy as np` -> `import jax.numpy as jnp`
`import numpy as onp` -> `import numpy as np`

and replace all references of `np` with `jnp` and `onp` with `np`.

**Comment by kancurochat** [comment]
Hi! I'm going to work on this. Could you please assign me this issue? Thanks beforehand :)

**Comment by rlouf** [comment]
Fixed in #73, that was fast!
