### ISSUE TITLE
pip3 install, module error

### ISSUE THREAD

**Issue by dirknbr** [rlouf/mcx#84]
I installed mcx via pip3 and then when I run `import mcx` I get 

``` 
ModuleNotFoundError: No module named 'mcx'
```

**Comment by rlouf** [comment]
That's normal, it hasn't been released yet (and before the `compiler-refactor` merge not really in a usable state!).

**Comment by dirknbr** [comment]
Ah ok, but I found it on the pypi site and assumed it can be installed

so install from github then?

**Comment by rlouf** [comment]
yes, `git clone` and `pip install .`
